### ISSUE TITLE
Add MDS package dependencies

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/docker-stacks#3]
@ecool50 - can you iterate over [this Dockerfile](https://github.com/UBC-DSCI/docker-stacks/blob/master/mds-grading/Dockerfile) so that it has the needed python package dependencies to grade the MDS labs? 

Packages that I imagine need to be added are:
- `altair`
- `graphviz` 
- any of their dependencies?

**Comment by ttimbers** [comment]
oops, here's the link: https://github.com/UBC-DSCI/docker-stacks/blob/master/mds-grading/Dockerfile

**Comment by ecool50** [comment]
Hi @ttimbers I will have a look at it!

**Comment by ecool50** [comment]
Hi @ttimbers 
I have updated the `Dockerfile `to include the installation of `graphviz`, `altair` and all the dependencies required to work. I also tested the file to make sure the plots do render when run from the docker file. Lastly, after some work, I got `nbgrader` to work with the integration of `graphviz` and `altair`. 
Please take a look and let me know your thoughts and/or concerns.
